//
//  HomeViewPresenter.swift
//  PeliculasNewTiss
//
//  Created Administrator on 12/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewPresenter {
    //MARK: - Protocol Properties
    weak private var view: HomeViewViewProtocol?
    var interactor: HomeViewInteractorProtocol?
    private let router: HomeViewWireframeProtocol
   
   

    //MARK: - Life Cycle
    init(interface: HomeViewViewProtocol, interactor: HomeViewInteractorProtocol?, router: HomeViewWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension HomeViewPresenter: HomeViewPresenterProtocol {
    func singOff() {
        router.singOff()
    }
    
    func detailPeli(dato: Int) {
        var adios = dato
        print("Conexion view ------> presenter \(dato)")
        router.showDetailMovie(dato: dato)
        
    }
   
    func info(peli: Movies) {
        view?.info(peli: peli)
    }
    
    func getData(moviType: MoviesType) {
        interactor?.getInitData(moviType: moviType)
    }
    

}

//MARK: - Private functions
extension HomeViewPresenter {
    
}
