//
//  ProfileProtocols.swift
//  PeliculasNewTiss
//
//  Created Administrator on 23/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProfileWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol ProfilePresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol ProfileInteractorProtocol: AnyObject {

  var presenter: ProfilePresenterProtocol?  { get set }
}

//MARK: View -
protocol ProfileViewProtocol: AnyObject {

  var presenter: ProfilePresenterProtocol?  { get set }
}
