//
//  ProfileInteractor.swift
//  PeliculasNewTiss
//
//  Created Administrator on 23/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileInteractor {
    //MARK: - Protocol Properties
    weak var presenter: ProfilePresenterProtocol?
}

//MARK: - Interactor Methods
extension ProfileInteractor: ProfileInteractorProtocol {
    
}
