//
//  ProfilePresenter.swift
//  PeliculasNewTiss
//
//  Created Administrator on 23/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfilePresenter {
    //MARK: - Protocol Properties
    weak private var view: ProfileViewProtocol?
    var interactor: ProfileInteractorProtocol?
    private let router: ProfileWireframeProtocol

    //MARK: - Life Cycle
    init(interface: ProfileViewProtocol, interactor: ProfileInteractorProtocol?, router: ProfileWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension ProfilePresenter: ProfilePresenterProtocol {
    
}

//MARK: - Private functions
extension ProfilePresenter {
    
}
