//
//  MovieDetailRouter.swift
//  PeliculasNewTiss
//
//  Created Administrator on 08/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovieDetailRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule(datos: Int) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MovieDetailViewController(nibName: nil, bundle: nil)
        let interactor = MovieDetailInteractor()
        let router = MovieDetailRouter()
        let presenter = MovieDetailPresenter(interface: view, interactor: interactor, router: router)
        print("dato ya esta en el nuevo viewController \(datos)")
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        view.idPelicula = datos
        return view
    }
}

//MARK: - Router Metods
extension MovieDetailRouter: MovieDetailWireframeProtocol {
    func showDetail(datos: String) {
        print("dato ya esta en el nuevo viewController showDetail \(datos)")
    }
    
}

//MARK: - Private functions
extension MovieDetailRouter {
    
}
