//
//  MovieDetailProtocols.swift
//  PeliculasNewTiss
//
//  Created Administrator on 08/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MovieDetailWireframeProtocol: AnyObject {
    func showDetail(datos: String)
}
//MARK: Presenter -
protocol MovieDetailPresenterProtocol: AnyObject {
    func getInitData(dato: Int)
    func info(peli: detailMovie)
}

//MARK: Interactor -
protocol MovieDetailInteractorProtocol: AnyObject {

  var presenter: MovieDetailPresenterProtocol?  { get set }
    func getInitData(dato: Int)
}

//MARK: View -
protocol MovieDetailViewProtocol: AnyObject {

  var presenter: MovieDetailPresenterProtocol?  { get set }
    func info(peli: detailMovie)
}
