//
//  MovieDetailPresenter.swift
//  PeliculasNewTiss
//
//  Created Administrator on 08/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovieDetailPresenter {
    //MARK: - Protocol Properties
    weak private var view: MovieDetailViewProtocol?
    var interactor: MovieDetailInteractorProtocol?
    private let router: MovieDetailWireframeProtocol

    //MARK: - Life Cycle
    init(interface: MovieDetailViewProtocol, interactor: MovieDetailInteractorProtocol?, router: MovieDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension MovieDetailPresenter: MovieDetailPresenterProtocol {
    func info(peli: detailMovie) {
        view?.info(peli: peli)
    }
    
    func getInitData(dato: Int) {
        interactor?.getInitData(dato: dato)
    }
    

    
}

//MARK: - Private functions
extension MovieDetailPresenter {
    
}
