//
//  ViewLoginPresenter.swift
//  PeliculasNewTiss
//
//  Created Administrator on 12/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ViewLoginPresenter {
    //MARK: - Protocol Properties
    weak private var view: ViewLoginViewProtocol?
    var interactor: ViewLoginInteractorProtocol?
    private let router: ViewLoginWireframeProtocol

    //MARK: - Life Cycle
    init(interface: ViewLoginViewProtocol, interactor: ViewLoginInteractorProtocol?, router: ViewLoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension ViewLoginPresenter: ViewLoginPresenterProtocol {
    func nextView() {
        router.nextView()
    }
    
    func loginSuccess() {
        view?.loginSuccess()
    }
    
    func loginFiel() {
        view?.loginFiel()
    }
    
    func initToken(pass: String, user: String) {
        interactor?.initToken(pass: pass, user: user)
    }
    
    
}

//MARK: - Private functions
extension ViewLoginPresenter {
    
}
