//
//  ViewLoginProtocols.swift
//  PeliculasNewTiss
//
//  Created Administrator on 12/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ViewLoginWireframeProtocol: AnyObject {
    
    func nextView()

}
//MARK: Presenter -
protocol ViewLoginPresenterProtocol: AnyObject {
    func initToken(pass: String, user: String)
    func loginSuccess()
    func loginFiel()
    func nextView()
}


//MARK: Interactor -
protocol ViewLoginInteractorProtocol: AnyObject {

  var presenter: ViewLoginPresenterProtocol?  { get set }
    
    func initToken(pass: String, user: String)
}

//MARK: View -
protocol ViewLoginViewProtocol: AnyObject {

  var presenter: ViewLoginPresenterProtocol?  { get set }
    func loginSuccess()
    func loginFiel()
   
    
}
