//
//  ViewLoginViewController.swift
//  PeliculasNewTiss
//
//  Created Administrator on 12/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit



class ViewLoginViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: ViewLoginPresenterProtocol?
    
    //MARK: - Properties
//    var loadingIndicator = UIActivityIndicatorView(style: .large)
    
    private var imageViewBackgroung : UIImageView = {
        let image = UIImageView()
        image.image = UIImage(named: "logo")
        return image
    }()
    
    private lazy var userTextfield : UITextField = {
        let textfield = UITextField()
        textfield.placeholder = "  Username"
        textfield.text = "fernando319408"
        textfield.layer.borderWidth = 1
        textfield.layer.cornerRadius = 2
        textfield.backgroundColor = .white
        textfield.textAlignment = .center
        textfield.attributedPlaceholder = NSAttributedString( string: "Username", attributes: [NSAttributedString.Key.foregroundColor: UIColor.gray])
        return textfield
    }()
    
    private lazy var paswordTextfield : UITextField = {
        let textfield = UITextField()
        textfield.placeholder = "  Password"
        textfield.text = "Fercho_31"
        textfield.layer.cornerRadius = 2
        textfield.layer.borderWidth = 1
        textfield.backgroundColor = .white
        textfield.isSecureTextEntry = true
        textfield.textAlignment = .center
        return textfield
    }()
    
    private lazy var buttonLogin : UIButton = {
        let button = UIButton()
        button.setTitle("Log in", for: .normal)
        button.backgroundColor = .systemGray
        button.layer.cornerRadius = 2
        button.addTarget(self, action: #selector(loginAacces), for: .touchUpInside)
        return button
    }()
    
    private var errorLabel : UILabel = {
        let label = UILabel()
        label.text = "Invalid username and/or password: you did not provide a valid login"
        label.textColor = .red
         if #available(iOS 16.0, *) {
            label.font = .systemFont(ofSize: 13, weight: .bold, width: .condensed)
        } else {
            // Fallback on earlier versions
        }
        label.isHidden = true
        return label
    }()
  
    //MARK: - Life Cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        initUi()
    }
    
    //MARK: - Methods
    
    
    private func initUi () {
        view.backgroundColor = .black
        
        view.addSubview(imageViewBackgroung)
        imageViewBackgroung.addAnchorsAndSize(width: width, height: height/2, left: nil, top: 0, right: nil, bottom: nil)
        
        view.addSubview(userTextfield)
        userTextfield.addAnchorsAndCenter(centerX: true, centerY: true, width: nil, height: 60, left: 60, top: nil, right: 60, bottom: nil)
        view.addSubview(paswordTextfield)
        paswordTextfield.addAnchorsAndCenter(centerX: true, centerY: nil, width: nil, height: 60, left: 60, top: 15, right: 60, bottom: nil, withAnchor: .top, relativeToView: userTextfield)
        view.addSubview(buttonLogin)
        buttonLogin.addAnchorsAndCenter(centerX: true, centerY: nil, width: nil, height: 60, left: 60, top: 15, right: 60, bottom: nil, withAnchor: .top, relativeToView: paswordTextfield)
        
        view.addSubview(errorLabel)
        errorLabel.addAnchorsAndCenter(centerX: true, centerY: nil, width: width, height: 30, left: nil, top: 15, right: nil, bottom: nil, withAnchor: .top, relativeToView: buttonLogin)
        
    }
    @objc private func loginAacces(){
        if userTextfield.text != "" && paswordTextfield.text != ""{
            print("no estan vacios")
            presenter?.initToken(pass: paswordTextfield.text ?? "", user: userTextfield.text ?? "")
//           loader
            errorLabel.isHidden = true
            
        }
        else{
            print("error en usuario o contrasena")
            errorLabel.isHidden = false
        }
    }
}

//MARK: - View Methods
extension ViewLoginViewController: ViewLoginViewProtocol {

    
    func loginSuccess() {
        print("Acceso correcto")
        presenter?.nextView()
//        loading parar
    }
    
    func loginFiel() {
        print("Acceso incorrecto")
//        loading parar
        errorLabel.isHidden = false
    }
    
    
}

//MARK: - Private functions
extension ViewLoginViewController {
    
}
